name: CI

# triggers
on:
  push:
    branches: ["master"]
  workflow_dispatch:

# what to do when triggered

jobs:
  runs-on: ubuntu-latest
  install:
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
  unit:
    needs: install
    steps:
      - name: unit test
        run: npm run test:unit
  integration:
    needs: install
    steps:
      - name: integration test
        run: npm run test:integration
